### ISSUE TITLE
 stloc.s num error

### ISSUE THREAD

**Issue by caozhiyuan** [brian-reichle/MethodCheck#1]
in https://github.com/brian-reichle/MethodCheck/blob/master/src/MethodCheck.Core/Parsing/ILReader.cs#L43,
should sbyte

**Comment by brian-reichle** [comment]
Yes, that's a bug :), but the spec says its unsigned (ECMA-335 Partition III Section 3.43) so the correct fix would be byte rather than sbyte.

Will have a fix soon.
